//! Input event representations for the OxiTerm protocol.
//!
//! This module defines the types of user input events captured by the terminal,
//! including keyboard keystrokes, mouse interactions, window resizing, and custom
//! hot-reload signaling events.

use serde::{Deserialize, Serialize};

/// High-level input events captured and processed by the OxiTerm engine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum InputEvent {
    /// A keyboard event representing a key press, repeat, or release.
    KeyPress(KeyEvent),
    /// A mouse interaction event (clicks, dragging, or scrolling).
    MouseEvent(MouseInput),
    /// Triggered when the client window columns or rows resize.
    Resize {
        /// The new width of the screen in characters.
        cols: u16,
        /// The new height of the screen in characters.
        rows: u16,
    },
    /// A response sequence containing device status/capability reports from the terminal.
    CapabilityResponse(Vec<u8>),
    /// Transmission On signal (XON), notifying to resume transmission.
    Xon,
    /// Transmission Off signal (XOFF), notifying to pause transmission.
    Xoff,
    /// Triggers a full terminal screen redraw request.
    Refresh,
    /// Triggers a hot-reload of the active template.
    Reload,
    /// Vertical scroll-up event inside the terminal screen.
    ScrollUp,
    /// Vertical scroll-down event inside the terminal screen.
    ScrollDown,
    /// Text typed into a focused input element.
    ///
    /// Generated by the session when the focused node has state binding enabled.
    TextInput(String),
    /// Signal indicating that the application state has been successfully patched.
    StatePatched,
    /// An unparsed or unrecognized escape sequence.
    Unknown(Vec<u8>),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_state_patched_serialization() {
        let event = InputEvent::StatePatched;
        let serialized = serde_json::to_string(&event).unwrap();
        assert_eq!(serialized, "\"StatePatched\"");
        let deserialized: InputEvent = serde_json::from_str(&serialized).unwrap();
        assert_eq!(deserialized, InputEvent::StatePatched);
    }
}

/// A structured representation of a keyboard event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KeyEvent {
    /// The decoded Unicode character of the key pressed.
    pub codepoint: char,
    /// The state of keyboard modifiers (Shift, Ctrl, Alt, etc.) at the time of the event.
    pub modifiers: KeyModifiers,
    /// The action type of the key (press, release, or repeat).
    pub kind: KeyKind,
}

/// The action type of a keyboard key interaction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyKind {
    /// Key was pressed down.
    Press,
    /// Key is being held down, triggering repeat strokes.
    Repeat,
    /// Key was released.
    Release,
}

/// Keyboard modifiers state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[allow(clippy::struct_excessive_bools)]
pub struct KeyModifiers {
    /// Shift key active.
    pub shift: bool,
    /// Ctrl key active.
    pub ctrl: bool,
    /// Alt key active.
    pub alt: bool,
    /// Meta key active.
    pub meta: bool,
    /// Shift lock is active.
    pub shift_lock: bool,
    /// Num lock is active.
    pub num_lock: bool,
}

/// A structured representation of a mouse event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MouseInput {
    /// The column index (0-based) where the event occurred.
    pub col: u16,
    /// The row index (0-based) where the event occurred.
    pub row: u16,
    /// The mouse button associated with the interaction.
    pub button: MouseButton,
    /// The type of action performed (press, release, move).
    pub action: MouseAction,
    /// Active keyboard modifiers during the mouse click/drag.
    pub modifiers: KeyModifiers,
}

/// Mouse buttons representing clicks and scroll wheel events.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MouseButton {
    /// Left mouse button.
    Left,
    /// Middle mouse button (often the scroll wheel button).
    Middle,
    /// Right mouse button.
    Right,
    /// Scroll wheel rotated up.
    WheelUp,
    /// Scroll wheel rotated down.
    WheelDown,
    /// Mouse movement without button actions.
    None,
}

/// The action type of a mouse interaction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MouseAction {
    /// A button was pressed down.
    Press,
    /// A button was released.
    Release,
    /// The mouse cursor was moved.
    Move,
}

pub mod decoder;
