services:
  spotify-app-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-app-server
    restart: unless-stopped
    ports:
      - "127.0.0.1:8889:8889"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - spotify-cache:/app/.cache

volumes:
  spotify-cache:
